from datetime import datetime


class SecurityLogger:
    """
    Records security events generated by MehAI.
    """

    def __init__(self):
        self.name = "MehAI Security Logger"
        self.events = []

    def log(self, event):
        timestamp = datetime.now().isoformat()

        record = {
            "timestamp": timestamp,
            "event": event
        }

        self.events.append(record)

        return record

    def get_events(self):
        return self.events